In [1]:
import pandas as pd

In [20]:
# csv_location = '/home/moose/Documents/python/la_ethics/covid_data/2020_04_07.06.all/Hospitalization_all_locs.csv'
csv_location = '/home/moose/Documents/python/la_ethics/covid_data/2020_04_09.04/Hospitalization_all_locs.csv'
df = pd.read_csv(csv_location)

In [21]:
df.head()

,V1,location_name,date,allbed_mean,allbed_lower,allbed_upper,ICUbed_mean,ICUbed_lower,ICUbed_upper,InvVen_mean,...,newICU_upper,totdea_mean,totdea_lower,totdea_upper,bedover_mean,bedover_lower,bedover_upper,icuover_mean,icuover_lower,icuover_upper
0,1,Wyoming,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Wyoming,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Wyoming,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Wyoming,2020-01-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Wyoming,2020-01-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
df.columns

Index(['V1', 'location_name', 'date', 'allbed_mean', 'allbed_lower',
       'allbed_upper', 'ICUbed_mean', 'ICUbed_lower', 'ICUbed_upper',
       'InvVen_mean', 'InvVen_lower', 'InvVen_upper', 'deaths_mean',
       'deaths_lower', 'deaths_upper', 'admis_mean', 'admis_lower',
       'admis_upper', 'newICU_mean', 'newICU_lower', 'newICU_upper',
       'totdea_mean', 'totdea_lower', 'totdea_upper', 'bedover_mean',
       'bedover_lower', 'bedover_upper', 'icuover_mean', 'icuover_lower',
       'icuover_upper'],
      dtype='object')

In [23]:
df.location_name.unique()

array(['Wyoming', 'Wisconsin', 'West Virginia', 'Washington', 'Virginia',
       'Vermont', 'Veneto', "Valle d'Aosta", 'Valencian Community',
       'Utah', 'United States of America', 'United Kingdom', 'Umbria',
       'Toscana', 'Thuringia', 'Texas', 'Tennessee', 'Switzerland',
       'Sweden', 'Spain', 'South Dakota', 'South Carolina', 'Slovenia',
       'Slovakia', 'Sicilia', 'Schleswig-Holstein', 'Saxony',
       'Saxony-Anhalt', 'Sardegna', 'Saarland', 'Romania', 'Rhode Island',
       'Rhineland-Palatinate', 'Puglia', 'Provincia autonoma di Trento',
       'Provincia autonoma di Bolzano', 'Portugal', 'Poland', 'Piemonte',
       'Pennsylvania', 'Other Counties, WA', 'Oregon', 'Oklahoma', 'Ohio',
       'Norway', 'North Rhine-Westphalia', 'North Dakota',
       'North Carolina', 'New York', 'New Mexico', 'New Jersey',
       'New Hampshire', 'Nevada', 'Netherlands', 'Nebraska', 'Navarre',
       'Murcia', 'Montana', 'Molise', 'Missouri', 'Mississippi',
       'Minnesota', 'Michigan', 'Melilla', 'Mecklenburg-Vorpommern',
       'Massachusetts', 'Maryland', 'Marche', 'Malta', 'Maine',
       'Luxembourg', 'Lower Saxony', 'Louisiana', 'Lombardia',
       'Lithuania', 'Liguria', 'Life Care Center, Kirkland, WA', 'Lazio',
       'Latvia', 'La Rioja',
       'King and Snohomish Counties (excluding Life Care Center), WA',
       'Kentucky', 'Kansas', 'Italy', 'Ireland', 'Iowa', 'Indiana',
       'Illinois', 'Idaho', 'Hungary', 'Hesse', 'Hawaii', 'Hamburg',
       'Greece', 'Germany', 'Georgia', 'Galicia', 'Friuli-Venezia Giulia',
       'France', 'Florida', 'Finland', 'Extremadura', 'Estonia',
       'Emilia-Romagna', 'District of Columbia', 'Denmark', 'Delaware',
       'Czechia', 'Cyprus', 'Croatia', 'Connecticut',
       'Community of Madrid', 'Colorado', 'Ceuta', 'Catalonia',
       'Castilla-La Mancha', 'Castile and Leon', 'Cantabria',
       'Canary Islands', 'Campania', 'California', 'Calabria', 'Bulgaria',
       'Bremen', 'Brandenburg', 'Berlin', 'Belgium', 'Bavaria',
       'Basque Country', 'Basilicata', 'Balearic Islands',
       'Baden-Wurttemberg', 'Austria', 'Asturias', 'Arkansas', 'Arizona',
       'Aragon', 'Andalucia', 'Alaska', 'Alabama', 'Abruzzo'],
      dtype=object)

In [24]:
df_austria = df[df.location_name == 'Austria']
df_austria

,V1,location_name,date,allbed_mean,allbed_lower,allbed_upper,ICUbed_mean,ICUbed_lower,ICUbed_upper,InvVen_mean,...,newICU_upper,totdea_mean,totdea_lower,totdea_upper,bedover_mean,bedover_lower,bedover_upper,icuover_mean,icuover_lower,icuover_upper
28380,1,Austria,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
28381,2,Austria,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
28382,3,Austria,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
28383,4,Austria,2020-01-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
28384,5,Austria,2020-01-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28590,211,Austria,2020-07-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,400.295,340.0,525.025,0.0,0.0,0.0,0.0,0.0,0.0
28591,212,Austria,2020-08-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,400.295,340.0,525.025,0.0,0.0,0.0,0.0,0.0,0.0
28592,213,Austria,2020-08-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,400.295,340.0,525.025,0.0,0.0,0.0,0.0,0.0,0.0
28593,214,Austria,2020-08-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,400.295,340.0,525.025,0.0,0.0,0.0,0.0,0.0,0.0
28594,215,Austria,2020-08-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,400.295,340.0,525.025,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
df_Louisiana = df[(df.location_name == 'Louisiana') & (df.date > '2020-03-20') & (df.date < '2020-04-10')]

df_Louisiana

,V1,location_name,date,allbed_mean,allbed_lower,allbed_upper,ICUbed_mean,ICUbed_lower,ICUbed_upper,InvVen_mean,...,newICU_upper,totdea_mean,totdea_lower,totdea_upper,bedover_mean,bedover_lower,bedover_upper,icuover_mean,icuover_lower,icuover_upper
15558,79,Louisiana,2020-03-21,345.311580,325.686979,363.533824,77.291458,75.785189,78.941258,74.385243,...,22.687500,16.0,16.0,16.0,0.0,0.0,0.0,0.0,0.0,0.000000
15559,80,Louisiana,2020-03-22,500.262107,477.685313,524.063235,113.883648,112.175905,115.882353,110.079749,...,39.500000,20.0,20.0,20.0,0.0,0.0,0.0,0.0,0.0,0.000000
15560,81,Louisiana,2020-03-23,574.948881,550.529412,600.472059,132.384142,130.235294,134.667308,127.017778,...,23.647549,35.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.000000
15561,82,Louisiana,2020-03-24,612.201091,586.408824,639.453646,135.659028,133.199412,138.062604,128.801174,...,19.437500,46.0,46.0,46.0,0.0,0.0,0.0,0.0,0.0,0.000000
15562,83,Louisiana,2020-03-25,709.988076,682.407721,740.176471,166.930708,163.733333,169.882353,157.180489,...,44.125208,65.0,65.0,65.0,0.0,0.0,0.0,0.0,0.0,0.000000
15563,84,Louisiana,2020-03-26,909.281795,877.124816,943.687960,205.962710,202.775980,208.942647,194.787221,...,59.466667,83.0,83.0,83.0,0.0,0.0,0.0,0.0,0.0,0.000000
15564,85,Louisiana,2020-03-27,986.421537,953.233824,1019.707353,225.017876,221.562500,228.176746,212.790844,...,38.400294,119.0,119.0,119.0,0.0,0.0,0.0,0.0,0.0,0.000000
15565,86,Louisiana,2020-03-28,1062.349685,1028.199554,1097.003333,233.841375,230.350784,237.235294,218.877847,...,46.600625,137.0,137.0,137.0,0.0,0.0,0.0,0.0,0.0,0.000000
15566,87,Louisiana,2020-03-29,1202.931100,1166.645588,1241.068125,288.599516,284.265882,292.589706,269.177929,...,74.814063,151.0,151.0,151.0,0.0,0.0,0.0,0.0,0.0,0.000000
15567,88,Louisiana,2020-03-30,1310.516481,1272.940980,1348.937674,320.208724,315.686979,324.439896,298.466748,...,48.647549,185.0,185.0,185.0,0.0,0.0,0.0,0.0,0.0,0.000000
15568,89,Louisiana,2020-03-31,1550.139105,1510.764338,1591.718842,362.013586,357.352941,366.472157,337.544650,...,78.438327,239.0,239.0,239.0,0.0,0.0,0.0,0.0,0.0,0.000000
15569,90,Louisiana,2020-04-01,1542.546368,1503.051225,1585.000000,356.798125,351.714076,361.923437,327.499519,...,51.375625,273.0,273.0,273.0,0.0,0.0,0.0,0.0,0.0,0.000000
15570,91,Louisiana,2020-04-02,1650.866244,1609.098438,1693.669444,401.064461,395.823254,406.463235,368.878513,...,81.000000,310.0,310.0,310.0,0.0,0.0,0.0,0.0,0.0,0.000000
15571,92,Louisiana,2020-04-03,1825.298036,1783.488971,1869.251103,446.569534,440.763235,452.313511,409.980018,...,88.313511,370.0,370.0,370.0,0.0,0.0,0.0,0.0,0.0,0.000000
15572,93,Louisiana,2020-04-04,1872.120099,1827.519748,1917.067647,442.274413,436.175392,448.070357,403.685084,...,60.000000,409.0,409.0,409.0,0.0,0.0,0.0,0.0,0.0,0.000000
15573,94,Louisiana,2020-04-05,1865.641729,1668.780882,2303.190385,466.616199,425.665278,559.175000,423.815268,...,156.448077,477.0,477.0,477.0,0.0,0.0,0.0,0.0,0.0,82.175000
15574,95,Louisiana,2020-04-06,1867.995421,1503.772222,2711.223214,454.693182,378.052778,630.875000,407.582224,...,143.224313,512.0,512.0,512.0,0.0,0.0,0.0,0.0,0.0,153.875000
15575,96,Louisiana,2020-04-07,1781.839086,1270.395833,2977.338187,463.383355,354.823611,710.801786,415.090874,...,126.203571,582.0,582.0,582.0,0.0,0.0,0.0,0.0,0.0,233.801786
15576,97,Louisiana,2020-04-08,1762.437427,1119.375000,3260.412500,438.353484,292.498611,768.732143,387.313060,...,133.516346,652.0,652.0,652.0,0.0,0.0,0.0,0.0,0.0,291.732143
15577,98,Louisiana,2020-04-09,1602.161567,849.466667,3359.017582,409.153465,231.606944,812.012500,355.630224,...,116.778846,702.0,702.0,702.0,0.0,0.0,0.0,0.0,0.0,335.012500